dist: xenial

language: node_js

node_js:
  - "10"

cache:
  directories:
  - node_modules
  - client/node_modules

script:
  - yarn lint
  - yarn build:ci
  - yarn test
  - cd client
  - yarn lint
  - yarn build
